
LP: main.cpp LinearProgram.cpp ReaderWriter.cpp LinearProgram.hpp ReaderWriter.hpp
	g++ main.cpp LinearProgram.cpp ReaderWriter.cpp -o LP.exe -std=c++11

cr:	LP run
	
run:
	./LP
	
clean:
	rm LP
